#!/usr/bin/env bash

function createdir {
	app="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
	source $app/create.sh
}

function removedir {
	source /usr/local/Cellar/repotap/1.1.6/lib/remove.sh
}
###

for arg in "$@"; do
  if [[ "$arg" = -c ]] || [[ "$arg" = create ]]; then
    ARG_CREATE_DIR=true
  fi
  if [[ "$arg" = -r ]] || [[ "$arg" = remove ]]; then
    ARG_REMOVE_DIR=true
  fi
done

###

if [[ "$ARG_CREATE_DIR" = true ]]; then
  createdir
fi

if [[ "$ARG_REMOVE_DIR" = true ]]; then
  removedir
fi
