#!/usr/bin/env bash
Cellar=$(brew --cellar repotap)

function createdir {
	source $Cellar/*/lib/create.sh
}

function removedir {
	source $Cellar/*/lib/remove.sh
}
###

for arg in "$@"; do
  if [[ "$arg" = -c ]] || [[ "$arg" = create ]]; then
    ARG_CREATE_DIR=true
  fi
  if [[ "$arg" = -r ]] || [[ "$arg" = remove ]]; then
    ARG_REMOVE_DIR=true
  fi
done

###

if [[ "$ARG_CREATE_DIR" = true ]]; then
  createdir
fi

if [[ "$ARG_REMOVE_DIR" = true ]]; then
  removedir
fi
